#No.12.py

#The sequence of triangle numbers is generated by adding the natural numbers.
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.



#Define a function that reads in a n-value and gets the nth triangle number


def tri(value):
    sum = 0
    for x in range(value+1):
        sum += x
    return sum

print(tri(7))


#Use triangle function to check how many divsors exist for that triangle number
